version: 2
jobs:
  build:
    working_directory: ~/poc
    docker:
     - image: circleci/openjdk:8-jdk-browsers
    steps:
     - checkout
     - run: mvn dependency:go-offline
     - run: mvn package
     - store_artifacts: 
        path target/poc-0.0.1-SNAPSHOT.jar